### ISSUE TITLE
This vs iCloud Core Data

### ISSUE THREAD

**Issue by malhal** [joulupukki/BTCloudKitSync#13]
Hi any info on why we should use this over ~~CloudKit~~ iCloud Core Data? Thanks.

**Comment by joulupukki** [comment]
Core Data, by itself, is just a local data storage mechanism. It doesn't automatically synchronize with CloudKit. There is an option to have your Core Data info synchronized with iCloud, but that's quite different from CloudKit.

So it all just depends on what you are using for your local data storage. This project is built to sync data from any type of local storage and isn't Core Data or SQLite specific.

Does this answer your question or is there more information you know about that would simplify things?

**Comment by malhal** [comment]
Sorry I meant "iCloud Core Data (edited first comment and title)", which syncs the local core data db with essentially a private database in iCloud. Since this project also syncs to the private CloudKit database I wasn't sure why you wouldn't just use that. But you are saying its to enable the use of different local storage, got it thanks for the reply. I'm working on a sync solution for the public database for partial syncs of relational data. Should be on Github soon.
